title: Phalcon License
app:
  name: Phalcon License
  author: 'Phalcon Team'
  description: 'Licenses governing the Phalcon Framework'
  keywords: ''
  generator: 'Github Pages'
  avatar: https://avatars3.githubusercontent.com/u/1221505?v=4

social:
  email: team@phalconphp.com
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

meta:
  analytics: 'UA-133802124-4'

permalink: /:title
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



