title: Phalcon License
app:
  name: Phalcon License
  author: 'Phalcon Team'
  description: 'Licenses governing the Phalcon Framework'
  keywords: 'phalcon, phalconpphp, zephir, license'
  avatar: https://avatars3.githubusercontent.com/u/1221505?v=4
  baseurl: "/"
  analytics: 'G-XRDKDE3CTC'
  cloudflare:
    analytics: 'a97087f228c541ac82f7134f1748af08'

url: https://license.phalcon.io
social:
  email: team@phalcon.io
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

permalink: /:title

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - serve
  - updateData.php
